import type { StarterState } from "./types";

export const starterState: StarterState = {
  schemaVersion: 1,
  updatedAt: "2026-01-15T10:24:00Z",
  workspace: {
    id: "sample-workspace",
    name: "Sample Workspace",
    project: "Website refresh",
    privacyBoundary: "local_only",
  },
  pipeline: [
    {
      id: "layout-review",
      stage: "Design review",
      item: "Update homepage layout",
      branch: "codex/homepage-layout",
      status: "Pending review",
      tone: "amber",
      updated: "Today, 10:24",
      decisionRequired: true,
    },
    {
      id: "hero-component",
      stage: "Implementation",
      item: "Hero section component",
      branch: "codex/hero-section",
      status: "In progress",
      tone: "blue",
      updated: "Today, 09:12",
      decisionRequired: false,
    },
    {
      id: "navigation",
      stage: "Implementation",
      item: "Navigation refactor",
      branch: "codex/navigation",
      status: "In progress",
      tone: "blue",
      updated: "Today, 08:50",
      decisionRequired: false,
    },
    {
      id: "responsive-checks",
      stage: "Testing",
      item: "Responsive checks",
      branch: "codex/responsive-checks",
      status: "Pending review",
      tone: "amber",
      updated: "Yesterday, 16:18",
      decisionRequired: true,
    },
    {
      id: "footer-update",
      stage: "Ready to commit",
      item: "Footer updates",
      branch: "codex/footer-updates",
      status: "Ready",
      tone: "green",
      updated: "Yesterday, 14:33",
      decisionRequired: false,
    },
    {
      id: "tokens-cleanup",
      stage: "Merged",
      item: "Color tokens cleanup",
      branch: "main",
      status: "Merged",
      tone: "green",
      updated: "Yesterday, 11:07",
      decisionRequired: false,
    },
  ],
  decisions: [
    {
      id: "homepage-layout",
      title: "Update homepage layout",
      context: "Improve hierarchy and clarity while preserving the approved content and navigation.",
      stage: "Design review",
      branch: "codex/homepage-layout",
      updated: "Today, 10:24",
      scope: [
        "Rework the opening section structure",
        "Update the feature list layout",
        "Adjust spacing and type scale",
      ],
      acceptanceCriteria: [
        "Layout remains usable at desktop and mobile widths",
        "Content hierarchy is clear",
        "Navigation behavior does not regress",
      ],
      consequences: {
        approved: "Proceed with implementation on a focused branch.",
        held: "Pause until more information is recorded.",
        rejected: "Revise the proposal before implementation.",
      },
    },
    {
      id: "responsive-review",
      title: "Review responsive checks",
      context: "Confirm the dashboard remains readable on each PC and at a narrow browser width.",
      stage: "Testing",
      branch: "codex/responsive-checks",
      updated: "Yesterday, 16:18",
      scope: ["Inspect desktop layout", "Inspect narrow layout", "Verify keyboard focus"],
      acceptanceCriteria: ["No horizontal overflow", "Primary controls remain visible", "Tables retain useful labels"],
      consequences: {
        approved: "Record responsive verification and merge the reviewed branch.",
        held: "Keep the branch open while issues are documented.",
        rejected: "Return the work for responsive fixes.",
      },
    },
  ],
  machines: [
    {
      id: "primary-pc",
      name: "Primary PC",
      status: "Ready",
      tone: "green",
      codex: "Running",
      workingTree: "Clean",
      branch: "codex/homepage-layout",
      lastCommit: "Today, 10:24",
    },
    {
      id: "secondary-pc",
      name: "Secondary PC",
      status: "Ready",
      tone: "green",
      codex: "Running",
      workingTree: "Clean",
      branch: "codex/responsive-checks",
      lastCommit: "Today, 10:20",
    },
  ],
  connections: [
    { id: "git", name: "Git repository", detail: "Reviewed source exchange", status: "Healthy", tone: "green" },
    { id: "dashboard", name: "Local dashboard", detail: "No private connector calls", status: "Healthy", tone: "green" },
    { id: "state", name: "Machine state", detail: "Independent on each PC", status: "Local", tone: "blue" },
  ],
  activity: [
    { id: "a1", time: "Today, 10:24", event: "Decision prepared", item: "Homepage layout", machine: "Primary PC", detail: "Awaiting owner review" },
    { id: "a2", time: "Today, 10:12", event: "Branch updated", item: "Hero component", machine: "Secondary PC", detail: "Focused commit pushed" },
    { id: "a3", time: "Today, 09:42", event: "Check completed", item: "Navigation", machine: "Primary PC", detail: "Build passed" },
    { id: "a4", time: "Yesterday, 16:18", event: "Decision held", item: "Responsive checks", machine: "Secondary PC", detail: "More evidence requested" },
  ],
  portableContext: {
    purpose: "Coordinate reviewed project work across two independent Codex installations.",
    sharedState: ["source", "sanitized_dashboard_state", "approved_decisions", "public_safe_evidence"],
    localState: ["codex_sessions", "memories", "credentials", "environment_files", "browser_state", "raw_client_data"],
    approvalProtocol: ["prepare_dashboard_entry", "owner_review", "record_decision", "implement_approved_scope", "verify_and_record_evidence"],
    nextActions: ["replace_fictional_state", "review_project_specific_agents_guidance", "validate_each_pc_independently"],
  },
};
